# Generated by Django 5.2.1 on 2025-05-14 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0002_alter_category_category_id_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderALL',
            fields=[
                ('OrderALL_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершён')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('order_all', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.orderall')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('Delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('addres', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('orderAll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.orderall')),
            ],
        ),
    ]
