# Generated by Django 5.2.1 on 2025-05-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
